name=input("enter the name:")
email=input("enter the email:")
address=input("enter the address:")
phn=int(input("enter the phnnum:"))
print("name:",name)
print("email",email)
print("address",address)
print("phnnum",phn)
